services:
  - type: web
    name: my-app
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: public
